import { useEffect, useState, useMemo } from "react";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "../firebase";

type Feedback = {
  id: string;
  name: string;
  feedback?: string;
  message?: string;
};

const FeedbackList = () => {
  const [realFeedbacks, setRealFeedbacks] = useState<Feedback[]>([]);
  const [index, setIndex] = useState(0);

  const DISPLAY_TOTAL = 906;

  const fakeReviews: Feedback[] = useMemo(() => {

    
    const  names =["Ajali Rao", "Suresh Raina", "Karan Mehra", "Swati Sharma", "Nikhil Kulkarni",
    "Meera Joshi", "Rakesh Pawar", "Anita Reddy", "Sanjay Bhosale", "Deepika Nair",
    "Arjun Verma", "Shweta Chavan", "Pratik Patil", "Aishwarya Deshmukh", "Vivek Sharma",
    "Sakshi Kulkarni", "Manoj Singh", "Ritu Joshi", "Siddharth Pawar", "Preeti Mehta",
    "Harsh Jain", "Aditi Rao", "Rohan Bhosale", "Neha Reddy", "Yash Chavan",
    "Kavita Sharma", "Abhishek Patil", "Tanvi Deshmukh", "Gaurav Kulkarni", "Anushka Joshi",
    "Pranav Pawar", "Simran Mehta", "Vikram Singh", "Pallavi Nair", "Saurabh Verma",
    "Ishita Chavan", "Kartik Sharma", "Riya Patil", "Aryan Deshmukh", "Shalini Kulkarni",
    "Mayank Joshi", "Divya Pawar", "Rajat Mehta", "Ananya Rao", "Tejas Bhosale",
    "Snehal Reddy", "Omkar Chavan", "Bhavna Sharma", "Sushant Patil", "Lavanya Deshmukh",
    "Nitin Kulkarni", "Vaishnavi Joshi", "Kunal Pawar", "Mansi Mehta", "Rohit Singh",
    "Priyanka Nair", "Aditya Verma", "Shruti Chavan", "Sameer Sharma", "Anika Patil",
    "Prashant Deshmukh", "Komal Kulkarni", "Harshit Joshi", "Riddhi Pawar", "Sanket Mehta",
    "Disha Rao", "Atharva Bhosale", "Poonam Reddy", "Dev Chavan", "Sonali Sharma",
    "Uday Patil", "Isha Deshmukh", "Yuvraj Kulkarni", "Nandini Joshi", "Sahil Pawar",
    "Aarohi Mehta", "Parth Singh", "Tanisha Nair", "Vihaan Verma", "Saanvi Chavan",
    "Arnav Sharma", "Myra Patil", "Reyansh Deshmukh", "Kiara Kulkarni", "Aarav Joshi",
    "Anvi Pawar", "Vedant Mehta", "Zara Rao", "Kabir Bhosale", "Aanya Reddy",
    "Shaurya Chavan", "Avni Sharma", "Rudra Patil", "Siya Deshmukh", "Dhruv Kulkarni",
    "Anaya Joshi", "Advait Pawar", "Ira Mehta", "Ayaan Singh", "Ria Nair",
    "Veer Verma", "Kyra Chavan", "Samay Sharma", "Nysa Patil", "Hridaan Deshmukh",
    "Aarohi Kulkarni", "Shourya Joshi", "Vanya Pawar", "Atharv Mehta", "Saisha Rao",
    "Reyansh Bhosale", "Prisha Reddy", "Aarush Chavan", "Navya Sharma", "Vihaan Patil",
    "Anika Deshmukh", "Devansh Kulkarni", "Saanvi Joshi", "Aarav Pawar", "Myra Mehta",
    "Rudra Singh", "Kiara Nair", "Dhruv Verma", "Anaya Chavan", "Advait Sharma",
    "Ira Patil", "Ayaan Deshmukh", "Ria Kulkarni", "Veer Joshi", "Kyra Pawar",
    "Samay Mehta", "Nysa Rao", "Hridaan Bhosale", "Aarohi Reddy", "Shourya Chavan",
    "Vanya Sharma", "Atharv Patil", "Saisha Deshmukh", "Reyansh Kulkarni", "Prisha Joshi",
    "Aarush Pawar", "Navya Mehta", "Vihaan Singh", "Anika Nair", "Devansh Verma",
    "Aanya Jadhav", "Aanya Patil", "Aanya Pawar", "Aarav Mehta", "Aarav Singh",
    "Aarav Verma", "Aarohi Bhosale", "Aarohi Jadhav", "Aarohi Kulkarni", "Aarohi Mehta",
    "Aarohi Shinde", "Aarohi Vyas", "Aarush Gaikwad", "Aarush Jadhav", "Aarush Patil",
    "Aarush Reddy", "Aarush Sharma", "Abhishek Mehta", "Abhishek Reddy", "Aditi Jain",
    "Aditi Kulkarni", "Aditi Thakur", "Aditya Jadhav", "Aditya Solanki", "Advait Bhosale",
    "Advait Deshmukh", "Advait Gaikwad", "Advait Salunke", "Aishwarya Chavan", "Aishwarya Nair",
    "Aishwarya Solanki", "Aishwarya Thakur", "Akash Bhosale", "Akash Kaur", "Akash Patil",
    "Akash Pawar", "Akash Shinde", "Akash Solanki", "Akash Thakur", "Amit Kaur",
    "Amit Kulkarni", "Amit Rao", "Amit Sharma", "Amit Vyas", "Ananya Kaur",
    "Ananya Mehta", "Ananya Nair", "Anaya Bhosale", "Anaya Gaikwad", "Anaya Jain",
    "Anaya Kaur", "Anaya Nair", "Anaya Patil", "Anaya Salunke", "Anaya Singh",
    "Anaya Yadav", "Anika Jain", "Anika Kaur", "Anika Malhotra", "Anika Mishra",
    "Anika More", "Anika Reddy", "Anita Desai", "Anita Jadhav", "Anita Shinde",
    "Anjali Agrawal", "Anjali More", "Anjali Nair", "Anjali Salunke", "Anushka Rao",
    "Anushka Verma", "Arjun Singh", "Arjun Thakur", "Arjun Vyas", "Arnav Pawar",
    "Aryan More", "Aryan Salunke", "Atharv Gaikwad", "Atharv Patil", "Atharv Pawar",
    "Atharv Sharma", "Atharv Verma", "Atharva Joshi", "Avni Chavan", "Avni Desai",
    "Avni More", "Avni Solanki", "Avni Verma", "Avni Vyas", "Ayaan Chavan",
    "Ayaan Jain", "Ayaan Joshi", "Ayaan More", "Ayaan Vyas", "Bhavna Singh",
    "Bhavna Vyas", "Deepika Kulkarni", "Deepika More", "Deepika Nair", "Dev Malhotra",
    "Dev Patil", "Dev Yadav", "Devansh Bhosale", "Devansh Joshi", "Devansh Singh",
    "Dhruv Desai", "Dhruv Kulkarni", "Dhruv More", "Dhruv Shinde", "Disha Mehta",
    "Disha Nair", "Disha Patil", "Disha Verma", "Disha Vyas", "Disha Yadav",
    "Divya Bhosale", "Divya Joshi", "Divya Shinde", "Divya Singh", "Gaurav Bhosale",
    "Gaurav Gaikwad", "Gaurav Mehta", "Gaurav Thakur", "Harsh Salunke", "Harsh Shinde",
    "Harsh Solanki", "Harshit Agrawal", "Harshit Malhotra", "Harshit More", "Harshit Thakur",
    "Hridaan Mishra", "Ira Bhosale", "Ira Desai", "Ira Jadhav", "Ira Joshi",
    "Ira Kaur", "Ira Reddy", "Ira Salunke", "Ira Shinde", "Ira Solanki",
    "Ira Vyas", "Isha Chavan", "Isha Jadhav", "Isha Joshi", "Isha Verma",
    "Isha Yadav", "Ishita Nair", "Ishita Sharma", "Kabir Chavan", "Kabir Nair",
    "Kabir Pawar", "Kabir Tripathi", "Kartik Pawar", "Kartik Singh", "Kavita Deshmukh",
    "Kavita Tripathi", "Kiara Chavan", "Kiara Kaur", "Kiara Kulkarni", "Kiara Malhotra",
    "Kiara Patil", "Kiara Sharma", "Kiara Solanki", "Kiara Yadav", "Komal Agrawal",
    "Komal Malhotra", "Komal Salunke", "Komal Sharma", "Kunal Mehta", "Kunal Rao",
    "Kunal Salunke", "Kunal Shinde", "Kunal Solanki", "Kyra Jadhav", "Lavanya Desai",
    "Lavanya Jain", "Manoj Chavan", "Manoj Jain", "Manoj Nair", "Manoj Solanki",
    "Manoj Yadav", "Mansi Mehta", "Mansi Nair", "Mansi Rao", "Mayank Deshmukh",
    "Mayank Kulkarni", "Mayank Rao", "Mayank Reddy", "Mayank Sharma", "Mayank Shinde",
    "Meera Deshmukh", "Meera Kaur", "Meera Thakur", "Myra Agrawal", "Myra Deshmukh",
    "Myra Jadhav", "Myra Rao", "Myra Vyas", "Nandini Gaikwad", "Nandini Joshi",
    "Nandini Tripathi", "Navya Chavan", "Neha Agrawal", "Neha Gaikwad", "Neha Mehta",
    "Neha Mishra", "Neha Pawar", "Nikhil Agrawal", "Nikhil Deshmukh", "Nikhil Nair",
    "Nikhil Rao", "Nysa Patil", "Nysa Salunke", "Nysa Singh", "Omkar Deshmukh",
    "Omkar Gaikwad", "Omkar Jain", "Omkar Kulkarni", "Omkar Mehta", "Omkar More",
    "Omkar Yadav", "Pallavi Kulkarni", "Parth Chavan", "Parth Gaikwad", "Parth Salunke",
    "Parth Tripathi", "Parth Yadav", "Pooja Chavan", "Poonam Jadhav", "Poonam Jain",
    "Poonam Joshi", "Poonam Rao", "Pranav Bhosale", "Pranav Gaikwad", "Pranav Mishra",
    "Pranav Rao", "Prashant Gaikwad", "Prashant Jain", "Prashant Kulkarni", "Prashant Tripathi",
    "Pratik Patil", "Pratik Rao", "Pratik Salunke", "Prisha Chavan", "Prisha Jain",
    "Prisha Sharma", "Priya Nair", "Priya Singh", "Priya Yadav", "Priyanka Agrawal",
    "Priyanka Vyas", "Rahul Salunke", "Rahul Tripathi", "Rajat Agrawal", "Rajat Deshmukh",
    "Rajat Mehta", "Rajat Patil", "Rajat Rao", "Rakesh Bhosale", "Reyansh Jadhav",
    "Reyansh More", "Reyansh Patil", "Reyansh Shinde", "Ria Deshmukh", "Ria Jain",
    "Ria Mishra", "Riddhi Kulkarni", "Riddhi Thakur", "Ritu Gaikwad", "Ritu Salunke",
    "Ritu Tripathi", "Riya Agrawal", "Riya More", "Rohan Jadhav", "Rohan Malhotra",
    "Rohan Mehta", "Rohit Patil", "Rohit Pawar", "Rohit Sharma", "Rohit Verma",
    "Rohit Yadav", "Sagar Bhosale", "Sagar Gaikwad", "Sagar Malhotra", "Sagar Patil",
    "Sagar Pawar", "Sagar Singh", "Sahil Bhosale", "Sahil Kaur", "Sahil More",
    "Saisha Chavan", "Saisha Malhotra", "Saisha Sharma", "Sakshi Mishra", "Samay Agrawal",
    "Samay Jadhav", "Samay Jain", "Samay Sharma", "Sameer Malhotra", "Sameer Shinde",
    "Sanjay Gaikwad", "Sanket Chavan", "Sanket Patil", "Sanket Pawar", "Sanket Rao",
    "Sanket Reddy", "Sanket Verma", "Sanket Yadav", "Saurabh Sharma", "Saurabh Vyas",
    "Shalini Chavan", "Shalini Desai", "Shalini More", "Shaurya Agrawal", "Shaurya Sharma",
    "Shourya Chavan", "Shourya Malhotra", "Shourya Rao", "Shruti Jadhav", "Shruti Kaur",
    "Shruti Pawar", "Shruti Salunke", "Shruti Thakur", "Shweta Gaikwad", "Shweta Patil",
    "Shweta Reddy", "Shweta Salunke", "Shweta Shinde", "Siddharth Jadhav", "Siddharth Pawar",
    "Siddharth Tripathi", "Siddharth Vyas", "Simran Jain", "Simran Singh", "Simran Vyas",
    "Siya Joshi", "Siya Sharma", "Snehal Agrawal", "Snehal Verma", "Sonali Mishra",
    "Sonali Solanki", "Sonali Tripathi", "Sonali Yadav", "Sushant Kaur", "Sushant Mehta",
    "Sushant Mishra", "Sushant Verma", "Swati Malhotra", "Tanisha Agrawal", "Tanisha Deshmukh",
    "Tanisha Pawar", "Tanvi Desai", "Tejas Solanki", "Tejas Verma", "Uday Gaikwad",
    "Uday Jain", "Uday Kulkarni", "Uday Mehta", "Uday Reddy", "Uday Sharma",
    "Uday Singh", "Uday Tripathi", "Vaishnavi Desai", "Vaishnavi Jadhav", "Vaishnavi Nair",
    "Vanya Chavan", "Vanya Kulkarni", "Vanya Thakur", "Vedant Desai", "Vedant Pawar",
    "Vedant Reddy", "Veer Chavan", "Veer Mehta", "Veer Mishra", "Veer Patil",
    "Veer Rao", "Veer Reddy", "Vihaan Bhosale", "Vihaan Deshmukh", "Vihaan Jain",
    "Vihaan Mishra", "Vihaan Thakur", "Vikas Joshi", "Vikas Kaur", "Vikas Solanki",
    "Vikram Thakur", "Vikram Yadav", "Vivek Desai", "Vivek Pawar", "Vivek Rao",
    "Yash Joshi", "Yash Rao", "Yash Shinde", "Yash Yadav", "Yuvraj Agrawal",
    "Yuvraj Deshmukh", "Yuvraj Kaur",
    "Aanya Jadhav", "Aanya Patil", "Aanya Pawar", "Aarav Mehta", "Aarav Singh",
    "Aarav Verma", "Aarohi Bhosale", "Aarohi Jadhav", "Aarohi Kulkarni", "Aarohi Mehta",
    "Aarohi Shinde", "Aarohi Vyas", "Aarush Gaikwad", "Aarush Jadhav", "Aarush Patil",
    "Aarush Reddy", "Aarush Sharma", "Abhishek Mehta", "Abhishek Reddy", "Aditi Jain",
    "Aditi Kulkarni", "Aditi Thakur", "Aditya Jadhav", "Aditya Solanki", "Advait Bhosale",
    "Advait Deshmukh", "Advait Gaikwad", "Advait Salunke", "Aishwarya Chavan", "Aishwarya Nair",
    "Aishwarya Solanki", "Aishwarya Thakur", "Akash Bhosale", "Akash Kaur", "Akash Patil",
    "Akash Pawar", "Akash Shinde", "Akash Solanki", "Akash Thakur", "Amit Kaur",
    "Amit Kulkarni", "Amit Rao", "Amit Sharma", "Amit Vyas", "Ananya Kaur",
    "Ananya Mehta", "Ananya Nair", "Anaya Bhosale", "Anaya Gaikwad", "Anaya Jain",
    "Anaya Kaur", "Anaya Nair", "Anaya Patil", "Anaya Salunke", "Anaya Singh",
    "Anaya Yadav", "Anika Jain", "Anika Kaur", "Anika Malhotra", "Anika Mishra",
    "Anika More", "Anika Reddy", "Anita Desai", "Anita Jadhav", "Anita Shinde",
    "Anjali Agrawal", "Anjali More", "Anjali Nair", "Anjali Salunke", "Anushka Rao",
    "Anushka Verma", "Arjun Singh", "Arjun Thakur", "Arjun Vyas", "Arnav Pawar",
    "Aryan More", "Aryan Salunke", "Atharv Gaikwad", "Atharv Patil", "Atharv Pawar",
    "Atharv Sharma", "Atharv Verma", "Atharva Joshi", "Avni Chavan", "Avni Desai",
    "Avni More", "Avni Solanki", "Avni Verma", "Avni Vyas", "Ayaan Chavan",
    "Ayaan Jain", "Ayaan Joshi", "Ayaan More", "Ayaan Vyas", "Bhavna Singh",
    "Bhavna Vyas", "Deepika Kulkarni", "Deepika More", "Deepika Nair", "Dev Malhotra",
    "Dev Patil", "Dev Yadav", "Devansh Bhosale", "Devansh Joshi", "Devansh Singh",
    "Dhruv Desai", "Dhruv Kulkarni", "Dhruv More", "Dhruv Shinde", "Disha Mehta",
    "Disha Nair", "Disha Patil", "Disha Verma", "Disha Vyas", "Disha Yadav",
    "Divya Bhosale", "Divya Joshi", "Divya Shinde", "Divya Singh", "Gaurav Bhosale",
    "Gaurav Gaikwad", "Gaurav Mehta", "Gaurav Thakur", "Harsh Salunke", "Harsh Shinde",
    "Harsh Solanki", "Harshit Agrawal", "Harshit Malhotra", "Harshit More", "Harshit Thakur",
    "Hridaan Mishra", "Ira Bhosale", "Ira Desai", "Ira Jadhav", "Ira Joshi",
    "Ira Kaur", "Ira Reddy", "Ira Salunke", "Ira Shinde", "Ira Solanki",
    "Ira Vyas", "Isha Chavan", "Isha Jadhav", "Isha Joshi", "Isha Verma",
    "Isha Yadav", "Ishita Nair", "Ishita Sharma", "Kabir Chavan", "Kabir Nair",
    "Kabir Pawar", "Kabir Tripathi", "Kartik Pawar", "Kartik Singh", "Kavita Deshmukh",
    "Kavita Tripathi", "Kiara Chavan", "Kiara Kaur", "Kiara Kulkarni", "Kiara Malhotra",
    "Kiara Patil", "Kiara Sharma", "Kiara Solanki", "Kiara Yadav", "Komal Agrawal",
    "Komal Malhotra", "Komal Salunke", "Komal Sharma", "Kunal Mehta", "Kunal Rao",
    "Kunal Salunke", "Kunal Shinde", "Kunal Solanki", "Kyra Jadhav", "Lavanya Desai",
    "Lavanya Jain", "Manoj Chavan", "Manoj Jain", "Manoj Nair", "Manoj Solanki",
    "Manoj Yadav", "Mansi Mehta", "Mansi Nair", "Mansi Rao", "Mayank Deshmukh",
    "Mayank Kulkarni", "Mayank Rao", "Mayank Reddy", "Mayank Sharma", "Mayank Shinde",
    "Meera Deshmukh", "Meera Kaur", "Meera Thakur", "Myra Agrawal", "Myra Deshmukh",
    "Myra Jadhav", "Myra Rao", "Myra Vyas", "Nandini Gaikwad", "Nandini Joshi",
    "Nandini Tripathi", "Navya Chavan", "Neha Agrawal", "Neha Gaikwad", "Neha Mehta",
    "Neha Mishra", "Neha Pawar", "Nikhil Agrawal", "Nikhil Deshmukh", "Nikhil Nair",
    "Nikhil Rao", "Nysa Patil", "Nysa Salunke", "Nysa Singh", "Omkar Deshmukh",
    "Omkar Gaikwad", "Omkar Jain", "Omkar Kulkarni", "Omkar Mehta", "Omkar More",
    "Omkar Yadav", "Pallavi Kulkarni", "Parth Chavan", "Parth Gaikwad", "Parth Salunke",
    "Parth Tripathi", "Parth Yadav", "Pooja Chavan", "Poonam Jadhav", "Poonam Jain",
    "Poonam Joshi", "Poonam Rao", "Pranav Bhosale", "Pranav Gaikwad", "Pranav Mishra",
    "Pranav Rao", "Prashant Gaikwad", "Prashant Jain", "Prashant Kulkarni", "Prashant Tripathi",
    "Pratik Patil", "Pratik Rao", "Pratik Salunke", "Prisha Chavan", "Prisha Jain",
    "Prisha Sharma", "Priya Nair", "Priya Singh", "Priya Yadav", "Priyanka Agrawal",
    "Priyanka Vyas", "Rahul Salunke", "Rahul Tripathi", "Rajat Agrawal", "Rajat Deshmukh",
    "Rajat Mehta", "Rajat Patil", "Rajat Rao", "Rakesh Bhosale", "Reyansh Jadhav",
    "Reyansh More", "Reyansh Patil", "Reyansh Shinde", "Ria Deshmukh", "Ria Jain",
    "Ria Mishra", "Riddhi Kulkarni", "Riddhi Thakur", "Ritu Gaikwad", "Ritu Salunke",
    "Ritu Tripathi", "Riya Agrawal", "Riya More", "Rohan Jadhav", "Rohan Malhotra",
    "Rohan Mehta", "Rohit Patil", "Rohit Pawar", "Rohit Sharma", "Rohit Verma",
    "Rohit Yadav", "Sagar Bhosale", "Sagar Gaikwad", "Sagar Malhotra", "Sagar Patil",
    "Sagar Pawar", "Sagar Singh", "Sahil Bhosale", "Sahil Kaur", "Sahil More",
    "Saisha Chavan", "Saisha Malhotra", "Saisha Sharma", "Sakshi Mishra", "Samay Agrawal",
    "Samay Jadhav", "Samay Jain", "Samay Sharma", "Sameer Malhotra", "Sameer Shinde",
    "Sanjay Gaikwad", "Sanket Chavan", "Sanket Patil", "Sanket Pawar", "Sanket Rao",
    "Sanket Reddy", "Sanket Verma", "Sanket Yadav", "Saurabh Sharma", "Saurabh Vyas",
    "Shalini Chavan", "Shalini Desai", "Shalini More", "Shaurya Agrawal", "Shaurya Sharma",
    "Shourya Chavan", "Shourya Malhotra", "Shourya Rao", "Shruti Jadhav", "Shruti Kaur",
    "Shruti Pawar", "Shruti Salunke", "Shruti Thakur", "Shweta Gaikwad", "Shweta Patil",
    "Shweta Reddy", "Shweta Salunke", "Shweta Shinde", "Siddharth Jadhav", "Siddharth Pawar",
    "Siddharth Tripathi", "Siddharth Vyas", "Simran Jain", "Simran Singh", "Simran Vyas",
    "Siya Joshi", "Siya Sharma", "Snehal Agrawal", "Snehal Verma", "Sonali Mishra",
    "Sonali Solanki", "Sonali Tripathi", "Sonali Yadav", "Sushant Kaur", "Sushant Mehta",
    "Sushant Mishra", "Sushant Verma", "Swati Malhotra", "Tanisha Agrawal", "Tanisha Deshmukh",
    "Tanisha Pawar", "Tanvi Desai", "Tejas Solanki", "Tejas Verma", "Uday Gaikwad",
    "Uday Jain", "Uday Kulkarni", "Uday Mehta", "Uday Reddy", "Uday Sharma",
    "Uday Singh", "Uday Tripathi", "Vaishnavi Desai", "Vaishnavi Jadhav", "Vaishnavi Nair",
    "Vanya Chavan", "Vanya Kulkarni", "Vanya Thakur", "Vedant Desai", "Vedant Pawar",
    "Vedant Reddy", "Veer Chavan", "Veer Mehta", "Veer Mishra", "Veer Patil",
    "Veer Rao", "Veer Reddy", "Vihaan Bhosale", "Vihaan Deshmukh", "Vihaan Jain",
    "Vihaan Mishra", "Vihaan Thakur", "Vikas Joshi", "Vikas Kaur", "Vikas Solanki",
    "Vikram Thakur", "Vikram Yadav", "Vivek Desai", "Vivek Pawar", "Vivek Rao",
    "Yash Joshi", "Yash Rao", "Yash Shinde", "Yash Yadav", "Yuvraj Agrawal",
    "Yuvraj Deshmukh", "Yuvraj Kaur",
    "Aanya Jadhav", "Aanya Patil", "Aanya Pawar", "Aarav Mehta", "Aarav Singh",
    "Aarav Verma", "Aarohi Bhosale", "Aarohi Jadhav", "Aarohi Kulkarni", "Aarohi Mehta",
    "Aarohi Shinde", "Aarohi Vyas", "Aarush Gaikwad", "Aarush Jadhav", "Aarush Patil",
    "Aarush Reddy", "Aarush Sharma", "Abhishek Mehta", "Abhishek Reddy", "Aditi Jain",
    "Aditi Kulkarni", "Aditi Thakur", "Aditya Jadhav", "Aditya Solanki", "Advait Bhosale",
    "Advait Deshmukh", "Advait Gaikwad", "Advait Salunke", "Aishwarya Chavan", "Aishwarya Nair",
    "Aishwarya Solanki", "Aishwarya Thakur", "Akash Bhosale", "Akash Kaur", "Akash Patil",
    "Akash Pawar", "Akash Shinde", "Akash Solanki", "Akash Thakur", "Amit Kaur",
    "Amit Kulkarni", "Amit Rao", "Amit Sharma", "Amit Vyas", "Ananya Kaur",
    "Ananya Mehta", "Ananya Nair", "Anaya Bhosale", "Anaya Gaikwad", "Anaya Jain",
    "Anaya Kaur", "Anaya Nair", "Anaya Patil", "Anaya Salunke", "Anaya Singh",
    "Anaya Yadav", "Anika Jain", "Anika Kaur", "Anika Malhotra", "Anika Mishra",
    "Anika More", "Anika Reddy", "Anita Desai", "Anita Jadhav", "Anita Shinde",
    "Anjali Agrawal", "Anjali More", "Anjali Nair", "Anjali Salunke", "Anushka Rao",
    "Anushka Verma", "Arjun Singh", "Arjun Thakur", "Arjun Vyas", "Arnav Pawar",
    "Aryan More", "Aryan Salunke", "Atharv Gaikwad", "Atharv Patil", "Atharv Pawar",
    "Atharv Sharma", "Atharv Verma", "Atharva Joshi", "Avni Chavan", "Avni Desai",
    "Avni More", "Avni Solanki", "Avni Verma", "Avni Vyas", "Ayaan Chavan",
    "Ayaan Jain", "Ayaan Joshi", "Ayaan More", "Ayaan Vyas", "Bhavna Singh",
    "Bhavna Vyas", "Deepika Kulkarni", "Deepika More", "Deepika Nair", "Dev Malhotra",
    "Dev Patil", "Dev Yadav", "Devansh Bhosale", "Devansh Joshi", "Devansh Singh",
    "Dhruv Desai", "Dhruv Kulkarni", "Dhruv More", "Dhruv Shinde", "Disha Mehta",
    "Disha Nair", "Disha Patil", "Disha Verma", "Disha Vyas", "Disha Yadav",
    "Divya Bhosale", "Divya Joshi", "Divya Shinde", "Divya Singh", "Gaurav Bhosale",
    "Gaurav Gaikwad", "Gaurav Mehta", "Gaurav Thakur", "Harsh Salunke", "Harsh Shinde",
    "Harsh Solanki", "Harshit Agrawal", "Harshit Malhotra", "Harshit More", "Harshit Thakur",
    "Hridaan Mishra", "Ira Bhosale", "Ira Desai", "Ira Jadhav", "Ira Joshi",
    "Ira Kaur", "Ira Reddy", "Ira Salunke", "Ira Shinde", "Ira Solanki",
    "Ira Vyas", "Isha Chavan", "Isha Jadhav", "Isha Joshi", "Isha Verma",
    "Isha Yadav", "Ishita Nair", "Ishita Sharma", "Kabir Chavan", "Kabir Nair",
    "Kabir Pawar", "Kabir Tripathi", "Kartik Pawar", "Kartik Singh", "Kavita Deshmukh",
    "Kavita Tripathi", "Kiara Chavan", "Kiara Kaur", "Kiara Kulkarni", "Kiara Malhotra",
    "Kiara Patil", "Kiara Sharma", "Kiara Solanki", "Kiara Yadav", "Komal Agrawal",
    "Komal Malhotra", "Komal Salunke", "Komal Sharma", "Kunal Mehta", "Kunal Rao",
    "Kunal Salunke", "Kunal Shinde", "Kunal Solanki", "Kyra Jadhav", "Lavanya Desai",
    "Lavanya Jain", "Manoj Chavan", "Manoj Jain", "Manoj Nair", "Manoj Solanki",
    "Manoj Yadav", "Mansi Mehta", "Mansi Nair", "Mansi Rao", "Mayank Deshmukh",
    "Mayank Kulkarni", "Mayank Rao", "Mayank Reddy", "Mayank Sharma", "Mayank Shinde",
    "Meera Deshmukh", "Meera Kaur", "Meera Thakur", "Myra Agrawal", "Myra Deshmukh",
    "Myra Jadhav", "Myra Rao", "Myra Vyas", "Nandini Gaikwad", "Nandini Joshi",
    "Nandini Tripathi", "Navya Chavan", "Neha Agrawal", "Neha Gaikwad", "Neha Mehta",
    "Neha Mishra", "Neha Pawar", "Nikhil Agrawal", "Nikhil Deshmukh", "Nikhil Nair",
    "Nikhil Rao", "Nysa Patil", "Nysa Salunke", "Nysa Singh", "Omkar Deshmukh",
    "Omkar Gaikwad", "Omkar Jain", "Omkar Kulkarni", "Omkar Mehta", "Omkar More",
    "Omkar Yadav", "Pallavi Kulkarni", "Parth Chavan", "Parth Gaikwad", "Parth Salunke",
    "Parth Tripathi", "Parth Yadav", "Pooja Chavan", "Poonam Jadhav", "Poonam Jain",
    "Poonam Joshi", "Poonam Rao", "Pranav Bhosale", "Pranav Gaikwad", "Pranav Mishra",
    "Pranav Rao", "Prashant Gaikwad", "Prashant Jain", "Prashant Kulkarni", "Prashant Tripathi",
    "Pratik Patil", "Pratik Rao", "Pratik Salunke", "Prisha Chavan", "Prisha Jain",
    "Prisha Sharma", "Priya Nair", "Priya Singh", "Priya Yadav", "Priyanka Agrawal",
    "Priyanka Vyas", "Rahul Salunke", "Rahul Tripathi", "Rajat Agrawal", "Rajat Deshmukh",
    "Rajat Mehta", "Rajat Patil", "Rajat Rao", "Rakesh Bhosale", "Reyansh Jadhav",
    "Reyansh More", "Reyansh Patil", "Reyansh Shinde", "Ria Deshmukh", "Ria Jain",
    "Ria Mishra", "Riddhi Kulkarni", "Riddhi Thakur", "Ritu Gaikwad", "Ritu Salunke",
    "Ritu Tripathi", "Riya Agrawal", "Riya More", "Rohan Jadhav", "Rohan Malhotra",
    "Rohan Mehta", "Rohit Patil", "Rohit Pawar", "Rohit Sharma", "Rohit Verma",
    "Rohit Yadav", "Sagar Bhosale", "Sagar Gaikwad", "Sagar Malhotra", "Sagar Patil",
    "Sagar Pawar", "Sagar Singh", "Sahil Bhosale", "Sahil Kaur", "Sahil More",
    "Saisha Chavan", "Saisha Malhotra", "Saisha Sharma", "Sakshi Mishra", "Samay Agrawal",
    "Samay Jadhav", "Samay Jain", "Samay Sharma", "Sameer Malhotra", "Sameer Shinde",
    "Sanjay Gaikwad", "Sanket Chavan", "Sanket Patil", "Sanket Pawar", "Sanket Rao",
    "Sanket Reddy", "Sanket Verma", "Sanket Yadav", "Saurabh Sharma", "Saurabh Vyas",
    "Shalini Chavan", "Shalini Desai", "Shalini More", "Shaurya Agrawal", "Shaurya Sharma",
    "Shourya Chavan", "Shourya Malhotra", "Shourya Rao", "Shruti Jadhav", "Shruti Kaur",
    "Shruti Pawar", "Shruti Salunke", "Shruti Thakur", "Shweta Gaikwad", "Shweta Patil",
    "Shweta Reddy", "Shweta Salunke", "Shweta Shinde", "Siddharth Jadhav", "Siddharth Pawar",
    "Siddharth Tripathi", "Siddharth Vyas", "Simran Jain", "Simran Singh", "Simran Vyas",
    "Siya Joshi", "Siya Sharma", "Snehal Agrawal", "Snehal Verma", "Sonali Mishra",
    "Sonali Solanki", "Sonali Tripathi", "Sonali Yadav", "Sushant Kaur", "Sushant Mehta",
    "Sushant Mishra", "Sushant Verma", "Swati Malhotra", "Tanisha Agrawal", "Tanisha Deshmukh",
    "Tanisha Pawar", "Tanvi Desai", "Tejas Solanki", "Tejas Verma", "Uday Gaikwad",
    "Uday Jain", "Uday Kulkarni", "Uday Mehta", "Uday Reddy", "Uday Sharma",
    "Uday Singh", "Uday Tripathi", "Vaishnavi Desai", "Vaishnavi Jadhav", "Vaishnavi Nair",
    "Vanya Chavan", "Vanya Kulkarni", "Vanya Thakur", "Vedant Desai", "Vedant Pawar",
    "Vedant Reddy", "Veer Chavan", "Veer Mehta", "Veer Mishra", "Veer Patil",
    "Veer Rao", "Veer Reddy", "Vihaan Bhosale", "Vihaan Deshmukh", "Vihaan Jain",
    "Vihaan Mishra", "Vihaan Thakur", "Vikas Joshi", "Vikas Kaur", "Vikas Solanki",
    "Vikram Thakur", "Vikram Yadav", "Vivek Desai", "Vivek Pawar", "Vivek Rao",
    "Yash Joshi", "Yash Rao", "Yash Shinde", "Yash Yadav", "Yuvraj Agrawal",
    "Yuvraj Deshmukh", "Yuvraj Kaur",
    "Saanvi Chavan", "Aarav Sharma"
  ];

      const quotes = [
        "Amazing gym with great environment.",
        "Very motivating workout sessions.",
        "Good trainers and equipment.",
        "Clean and well maintained gym.",
        "Highly recommended for fitness lovers.",
        "Best gym experience so far.",
        "The atmosphere here is electric!",
        "Professional staff and top-notch machines.",
        "Transformative experience for my health.",
        "Love the community feel here.",
        "Great place to achieve fitness goals.",
        "Friendly trainers and supportive staff.",
        "Modern equipment and clean space.",
        "Perfect gym for beginners and pros.",
        "Affordable pricing with great value.",
        "Positive vibes and motivating environment.",
        "Excellent guidance from trainers.",
        "Spacious gym with all facilities.",
        "Best decision to join this gym.",
        "Energetic and friendly atmosphere.",
        "Top quality machines and equipment.",
        "Great support from fitness coaches.",
        "Nice ambience and good music.",
        "Highly motivating trainers.",
        "Very professional and helpful staff.",
        "Excellent gym with great facilities.",
        "Clean, safe, and well equipped.",
        "Best gym in the area.",
        "Amazing transformation results.",
        "Good crowd and positive energy.",
        "Perfect place to stay fit.",
        "Very inspiring fitness environment.",
        "Trainers are very knowledgeable.",
        "Best place for weight training.",
        "Supportive fitness community.",
        "Great place for body transformation.",
        "Awesome experience every day.",
        "Perfect mix of cardio and strength training.",
        "Friendly people and great vibe.",
        "Amazing gym with great environment.",
    "Very motivating workout sessions.",
    "Good trainers and equipment.",
    "Clean and well maintained gym.",
    "Highly recommended for fitness lovers.",
    "Best gym experience so far.",
    "The atmosphere here is electric!",
    "Professional staff and top-notch machines.",
    "Transformative experience for my health.",
    "Love the community feel here.",
    "Fantastic results with consistent training at RMT.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Great place to achieve fitness goals.",
    "Friendly trainers and supportive staff.",
    "Modern equipment and clean space.",
    "Perfect gym for beginners and pros.",
    "Affordable pricing with great value.",
    "Very hygienic and well organized.",
    "Positive vibes and motivating environment.",
    "Excellent guidance from trainers.",
    "Spacious gym with all facilities.",
    "Best decision to join this gym.",
    "Very disciplined and well-managed at RMT.", 
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Energetic and friendly atmosphere.",
    "Top quality machines and equipment.",
    "Very clean and well maintained place.",
    "Great support from fitness coaches.",
    "Nice ambience and good music.",
    "Perfect place for daily workouts.",
    "Highly motivating trainers.",
    "Loved the workout sessions here.",
    "Very professional and helpful staff.",
    "Good environment for fitness lovers.",

    "Excellent gym with great facilities.",
    "Clean, safe, and well equipped.",
    "Best gym in the area.",
    "Trainers give proper attention.",
    "Amazing transformation results.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Well managed and organized gym.",
    "Good crowd and positive energy.",
    "Perfect place to stay fit.",
    "Loved the overall experience.",
    "Very inspiring fitness environment.",

    "Good pricing and great service.",
    "Trainers are very knowledgeable.",
    "Clean locker rooms and equipment.",
    "Best place for weight training.",
    "Nice setup and proper ventilation.",
    "Very comfortable workout space.",
    "Supportive fitness community.",
    "Great place for body transformation.",
    "Awesome experience every day.",
    "Highly satisfied with the service.",

    "Perfect mix of cardio and strength training.",
    "Friendly people and great vibe.",
    "The trainers here really push you to improve.",
    "Excellent and hygienic environment.",
    "Loving the variety of equipment and clean space.",
    "Great music and energetic atmosphere.",
    "Trainers give personal attention during workouts.",
    "Very professional and helpful trainers.",
    "Intense yet enjoyable sessions in a positive environment.",
    "Motivating crowd and uplifting energy.",
    "Trainers correct your form perfectly.",
    "Never felt bored — the environment keeps me engaged.",
    "Perfect gym for both beginners and pros.",
    "Amazing results thanks to the supportive trainers.",
    "Very spacious and well-ventilated gym.",
    "The positive vibe here makes me come back daily.",
    "Top-notch cleanliness and maintenance.",
    "Trainers are very encouraging and motivating.",
    "Friendly community and great gym environment.",
    "Challenging workouts in a refreshing atmosphere.",
    "Modern machines in a clean and organized space.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Trainers make every session feel worthwhile.",
    "Love the early morning energetic environment.",
    "Fantastic place to build strength with expert trainers.",
    "Great for weight loss with motivating trainers.",
    "The gym environment is always fresh and clean.",
    "Energizing atmosphere throughout the day.",
    "Amazing gym with great environment.",
    "Very motivating workout sessions.",
    "Good trainers and equipment.",
    "Clean and well maintained gym.",
    "Highly recommended for fitness lovers.",
    "Best gym experience so far.",
    "The atmosphere here is electric!",
    "Professional staff and top-notch machines.",
    "Transformative experience for my health.",
    "Love the community feel here.",
    "Fantastic results with consistent training at RMT.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Great place to achieve fitness goals.",
    "Friendly trainers and supportive staff.",
    "Modern equipment and clean space.",
    "Perfect gym for beginners and pros.",
    "Affordable pricing with great value.",
    "Very hygienic and well organized.",
    "Positive vibes and motivating environment.",
    "Excellent guidance from trainers.",
    "Spacious gym with all facilities.",
    "Best decision to join this gym.",
    "Very disciplined and well-managed at RMT.", 
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Energetic and friendly atmosphere.",
    "Top quality machines and equipment.",
    "Very clean and well maintained place.",
    "Great support from fitness coaches.",
    "Nice ambience and good music.",
    "Perfect place for daily workouts.",
    "Highly motivating trainers.",
    "Loved the workout sessions here.",
    "Very professional and helpful staff.",
    "Good environment for fitness lovers.",

    "Excellent gym with great facilities.",
    "Clean, safe, and well equipped.",
    "Best gym in the area.",
    "Trainers give proper attention.",
    "Amazing transformation results.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Well managed and organized gym.",
    "Good crowd and positive energy.",
    "Perfect place to stay fit.",
    "Loved the overall experience.",
    "Very inspiring fitness environment.",

    "Good pricing and great service.",
    "Trainers are very knowledgeable.",
    "Clean locker rooms and equipment.",
    "Best place for weight training.",
    "Nice setup and proper ventilation.",
    "Very comfortable workout space.",
    "Supportive fitness community.",
    "Great place for body transformation.",
    "Awesome experience every day.",
    "Highly satisfied with the service.",

    "Perfect mix of cardio and strength training.",
    "Friendly people and great vibe.",
    "The trainers here really push you to improve.",
    "Excellent and hygienic environment.",
    "Loving the variety of equipment and clean space.",
    "Great music and energetic atmosphere.",
    "Trainers give personal attention during workouts.",
    "Very professional and helpful trainers.",
    "Intense yet enjoyable sessions in a positive environment.",
    "Motivating crowd and uplifting energy.",
    "Trainers correct your form perfectly.",
    "Never felt bored — the environment keeps me engaged.",
    "Perfect gym for both beginners and pros.",
    "Amazing results thanks to the supportive trainers.",
    "Very spacious and well-ventilated gym.",
    "The positive vibe here makes me come back daily.",
    "Top-notch cleanliness and maintenance.",
    "Trainers are very encouraging and motivating.",
    "Friendly community and great gym environment.",
    "Challenging workouts in a refreshing atmosphere.",
    "Modern machines in a clean and organized space.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Trainers make every session feel worthwhile.",
    "Love the early morning energetic environment.",
    "Fantastic place to build strength with expert trainers.",
    "Great for weight loss with motivating trainers.",
    "The gym environment is always fresh and clean.",
    "Energizing atmosphere throughout the day.",
    "Trainers track your progress and motivate you.",
    "Super motivating environment every single visit.",
    "Clean lockers, showers, and peaceful vibe.",
    "Fun group classes in a lively environment.",
    "Improved my stamina drastically thanks to the trainers.",
    "Great place to meet fitness enthusiasts.",
    "Equipment is always well-maintained in a clean space.",
    "Loving every session in this positive environment.",
    "Trainers are certified and very knowledgeable.",
    "Perfect lighting and upbeat music in the gym.",
    "Helped me achieve my fitness goals with great guidance.",
    "Safe, secure, and welcoming environment.",
    "Best variety of workout options in a spacious gym.",
    "Staff and trainers are polite and helpful.",
    "Never overcrowded — comfortable and calm environment.",
    "Great for building muscle with proper trainer support.",
    "Well-organized workout zones and clean floors.",
    "The motivation level in this gym is contagious.",
    "Clean, refreshing AC environment all day.",
    "Trainers focus on technique and safety.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "The motivation level is contagious at RMT.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",

    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Super friendly and supportive trainers.",
    "Loving the visible progress with trainer guidance.",
    "Best gym atmosphere in the city.",
    "Trainers regularly check and correct your form.",
    "Very comfortable and modern changing rooms.",
    "Intense HIIT sessions in an energetic environment.",
    "Best place for complete body transformation.",
    "Always fresh and energetic crowd in the gym.",
    "Excellent recovery and stretching zone.",
    "Highly recommended gym with amazing trainers.",
    "Trainers make workouts fun and effective.",
    "Clean, modern, and powerful gym environment.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "The motivation level is contagious at RMT.",
    "Completely transformed my fitness level here.",
    "Best decision for my health and body.",
    "The trainers here genuinely care about your progress.",
    "Amazing gym experience every single day.",
    "Supportive trainers and calm yet energetic vibe.",
    "Outstanding environment for focused workouts.",
    "Trainers create a motivating and safe space.",
    "The overall atmosphere keeps me consistent.",
    "Best trainers who explain every exercise clearly.",
    "Spacious, clean, and well-lit gym environment.",
    "Trainers track your progress and motivate you.",
    "Super motivating environment every single visit.",
    "Clean lockers, showers, and peaceful vibe.",
    "Fun group classes in a lively environment.",
    "Improved my stamina drastically thanks to the trainers.",
    "Great place to meet fitness enthusiasts.",
    "Equipment is always well-maintained in a clean space.",
    "Loving every session in this positive environment.",
    "Trainers are certified and very knowledgeable.",
    "Perfect lighting and upbeat music in the gym.",
    "Helped me achieve my fitness goals with great guidance.",
    "Safe, secure, and welcoming environment.",
    "Best variety of workout options in a spacious gym.",
    "Staff and trainers are polite and helpful.",
    "Never overcrowded — comfortable and calm environment.",
    "Great for building muscle with proper trainer support.",
    "Well-organized workout zones and clean floors.",
    "The motivation level in this gym is contagious.",
    "Clean, refreshing AC environment all day.",
    "Trainers focus on technique and safety.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "The motivation level is contagious at RMT.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",

    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Super friendly and supportive trainers.",
    "Loving the visible progress with trainer guidance.",
    "Best gym atmosphere in the city.",
    "Trainers regularly check and correct your form.",
    "Very comfortable and modern changing rooms.",
    "Intense HIIT sessions in an energetic environment.",
    "Best place for complete body transformation.",
    "Always fresh and energetic crowd in the gym.",
    "Excellent recovery and stretching zone.",
    "Highly recommended gym with amazing trainers.",
    "Trainers make workouts fun and effective.",
    "Clean, modern, and powerful gym environment.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "The motivation level is contagious at RMT.",
    "Completely transformed my fitness level here.",
    "Best decision for my health and body.",
    "The trainers here genuinely care about your progress.",
    "Amazing gym experience every single day.",
    "Supportive trainers and calm yet energetic vibe.",
    "Outstanding environment for focused workouts.",
    "Trainers create a motivating and safe space.",
    "The overall atmosphere keeps me consistent.",
    "Best trainers who explain every exercise clearly.",
    "Spacious, clean, and well-lit gym environment.",
    "Amazing gym with great environment.",
    "Very motivating workout sessions.",
    "Good trainers and equipment.",
    "Clean and well maintained gym.",
    "Highly recommended for fitness lovers.",
    "Best gym experience so far.",
    "The atmosphere here is electric!",
    "Professional staff and top-notch machines.",
    "Transformative experience for my health.",
    "Love the community feel here.",
    "Fantastic results with consistent training at RMT.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Great place to achieve fitness goals.",
    "Friendly trainers and supportive staff.",
    "Modern equipment and clean space.",
    "Perfect gym for beginners and pros.",
    "Affordable pricing with great value.",
    "Very hygienic and well organized.",
    "Positive vibes and motivating environment.",
    "Excellent guidance from trainers.",
    "Spacious gym with all facilities.",
    "Best decision to join this gym.",
    "Very disciplined and well-managed at RMT.", 
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Energetic and friendly atmosphere.",
    "Top quality machines and equipment.",
    "Very clean and well maintained place.",
    "Great support from fitness coaches.",
    "Nice ambience and good music.",
    "Perfect place for daily workouts.",
    "Highly motivating trainers.",
    "Loved the workout sessions here.",
    "Very professional and helpful staff.",
    "Good environment for fitness lovers.",

    "Excellent gym with great facilities.",
    "Clean, safe, and well equipped.",
    "Best gym in the area.",
    "Trainers give proper attention.",
    "Amazing transformation results.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Well managed and organized gym.",
    "Good crowd and positive energy.",
    "Perfect place to stay fit.",
    "Loved the overall experience.",
    "Very inspiring fitness environment.",

    "Good pricing and great service.",
    "Trainers are very knowledgeable.",
    "Clean locker rooms and equipment.",
    "Best place for weight training.",
    "Nice setup and proper ventilation.",
    "Very comfortable workout space.",
    "Supportive fitness community.",
    "Great place for body transformation.",
    "Awesome experience every day.",
    "Highly satisfied with the service.",

    "Perfect mix of cardio and strength training.",
    "Friendly people and great vibe.",
    "The trainers here really push you to improve.",
    "Excellent and hygienic environment.",
    "Loving the variety of equipment and clean space.",
    "Great music and energetic atmosphere.",
    "Trainers give personal attention during workouts.",
    "Very professional and helpful trainers.",
    "Intense yet enjoyable sessions in a positive environment.",
    "Motivating crowd and uplifting energy.",
    "Trainers correct your form perfectly.",
    "Never felt bored — the environment keeps me engaged.",
    "Perfect gym for both beginners and pros.",
    "Amazing results thanks to the supportive trainers.",
    "Very spacious and well-ventilated gym.",
    "The positive vibe here makes me come back daily.",
    "Top-notch cleanliness and maintenance.",
    "Trainers are very encouraging and motivating.",
    "Friendly community and great gym environment.",
    "Challenging workouts in a refreshing atmosphere.",
    "Modern machines in a clean and organized space.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Trainers make every session feel worthwhile.",
    "Love the early morning energetic environment.",
    "Fantastic place to build strength with expert trainers.",
    "Great for weight loss with motivating trainers.",
    "The gym environment is always fresh and clean.",
    "Energizing atmosphere throughout the day.",
    "Trainers track your progress and motivate you.",
    "Super motivating environment every single visit.",
    "Clean lockers, showers, and peaceful vibe.",
    "Fun group classes in a lively environment.",
    "Improved my stamina drastically thanks to the trainers.",
    "Great place to meet fitness enthusiasts.",
    "Equipment is always well-maintained in a clean space.",
    "Loving every session in this positive environment.",
    "Trainers are certified and very knowledgeable.",
    "Perfect lighting and upbeat music in the gym.",
    "Helped me achieve my fitness goals with great guidance.",
    "Safe, secure, and welcoming environment.",
    "Best variety of workout options in a spacious gym.",
    "Staff and trainers are polite and helpful.",
    "Never overcrowded — comfortable and calm environment.",
    "Great for building muscle with proper trainer support.",
    "Well-organized workout zones and clean floors.",
    "The motivation level in this gym is contagious.",
    "Clean, refreshing AC environment all day.",
    "Trainers focus on technique and safety.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "The motivation level is contagious at RMT.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",

    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "Super friendly and supportive trainers.",
    "Loving the visible progress with trainer guidance.",
    "Best gym atmosphere in the city.",
    "Trainers regularly check and correct your form.",
    "Very comfortable and modern changing rooms.",
    "Intense HIIT sessions in an energetic environment.",
    "Best place for complete body transformation.",
    "Always fresh and energetic crowd in the gym.",
    "Excellent recovery and stretching zone.",
    "Highly recommended gym with amazing trainers.",
    "Trainers make workouts fun and effective.",
    "Clean, modern, and powerful gym environment.",
    "Fantastic results with consistent trainer guidance.",
    "Very affordable yet premium gym environment.",
    "Love the community challenges and positive vibe.",
    "Excellent pre and post workout recovery area.",
    "Best place to relieve stress — great environment.",
    "Trainers are like personal coaches here.",
    "Great focus on functional training with expert trainers.",
    "Always positive and uplifting gym atmosphere.",
    "Spacious floor for comfortable group training.",
    "Best gym to start your fitness journey.",
    "Very disciplined and well-managed environment.",
    "Trainers motivate you constantly during sessions.",
    "Cleanest gym environment I’ve ever joined.",
    "Perfect balance of strength and cardio with good trainers.",
    "Great for all age groups in a friendly environment.",
    "The motivation level is contagious at RMT.",
    "Completely transformed my fitness level here.",
    "Best decision for my health and body.",
    "The trainers here genuinely care about your progress.",
    "Amazing gym experience every single day.",
    "Supportive trainers and calm yet energetic vibe.",
    "Outstanding environment for focused workouts.",
    "Trainers create a motivating and safe space.",
    "The overall atmosphere keeps me consistent.",
    "Best trainers who explain every exercise clearly.",
    "Spacious, clean, and well-lit gym environment.",
      ];

    return Array.from({ length: DISPLAY_TOTAL }, (_, i) => ({
      id: `fake-${i}`,
      name: names[i % names.length],
      feedback: quotes[i % quotes.length],
    }));

  }, []);

  useEffect(() => {
    const unsubscribe = onSnapshot(collection(db, "feedbacks"), (snapshot) => {
      const data: Feedback[] = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...(doc.data() as Omit<Feedback, "id">),
      }));
      setRealFeedbacks(data);
    });

    return () => unsubscribe();
  }, []);

  const allReviews = useMemo(() => {
    const combined = [...realFeedbacks, ...fakeReviews];
    return combined.slice(0, DISPLAY_TOTAL);
  }, [realFeedbacks, fakeReviews]);

  useEffect(() => {
    if (allReviews.length === 0) return;

    const interval = setInterval(() => {
      setIndex((prev) =>
        prev < DISPLAY_TOTAL - 1 ? prev + 1 : prev
      );
    }, 3000);

    return () => clearInterval(interval);
  }, [allReviews.length]);

  if (allReviews.length === 0) {
    return (
      <p className="text-center text-gray-400 mt-10">
        Loading reviews...
      </p>
    );
  }

  const prev = () =>
    setIndex((p) => (p > 0 ? p - 1 : 0));

  const next = () =>
    setIndex((p) =>
      p < DISPLAY_TOTAL - 1 ? p + 1 : p
    );

  const current = allReviews[index];

  return (
    <div className="max-w-3xl mx-auto text-center px-4">
      <div className="bg-black border border-gray-700 rounded-2xl p-10 shadow-xl min-h-[350px] flex flex-col justify-center">

        <div className="text-[#18249E] text-6xl mb-2 font-serif">“</div>

        <div className="min-h-[100px] flex items-center justify-center">
          <p className="text-gray-300 text-lg md:text-xl italic leading-relaxed">
            {current.feedback || current.message}
          </p>
        </div>

        <p className="text-[#18249E] font-bold text-xl mt-6 tracking-wide">
          — {current.name}
        </p>

        <div className="flex flex-col items-center mt-10">

          <div className="flex gap-8">

            {index > 0 && (
              <button
                onClick={prev}
                className="w-12 h-12 border border-gray-600 rounded-full text-white text-2xl hover:bg-[#18249E]"
              >
                ‹
              </button>
            )}

            {index < DISPLAY_TOTAL - 1 && (
              <button
                onClick={next}
                className="w-12 h-12 border border-gray-600 rounded-full text-white text-2xl hover:bg-[#18249E]"
              >
                ›
              </button>
            )}

          </div>

          <p className="text-gray-500 text-xs mt-3 uppercase tracking-widest">
            Review {index + 1} of {DISPLAY_TOTAL}
          </p>

        </div>
      </div>
    </div>
  );
};

export default FeedbackList;
